spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/local
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create  # 테이블 자동 생성 (처음엔 create, 이후 update로 변경 가능)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
